services:
  - type: web
    name: lifequest-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://balrajsinghcoc_db_user:rC1ZsCXHDMRwSU3p@cluster0.pz5nwgq.mongodb.net/lifequest
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
